---
 - hosts: awx-proxy
   #become_user: azureuser
   become: yes
   tasks:
      - name: Check Proxy configuration
        command: cat /etc/nginx/nginx.conf |grep /etc/nginx/passthrough.conf
        register: results
