---
 - hosts: awx-proxy
   become: yes
   tasks:
    - name: Check Proxy configuration
      shell: cat /etc/nginx/nginx.conf |grep /etc/nginx/passthrough.conf
      register: results

    - name: Print the results
      debug:
        msg: "{{ results }}"
