
---
- hosts: all
  gather_facts: no
  tasks:
    - name: gather facts from apps
      setup:
      register: find_output
    
    - name: save 
      copy: 
        content: "{{ find_output }}" 
        dest: /home/azureuser/{{ inventory_hostname }}
    
    - name: Facts have been gathered
      debug:
        msg: "Facts are now gathered"
