---
 - hosts: AWX
   become: yes
   become_user: "{{ username }}"
   environment:
     - PATH: '{{ lookup(''env'', ''PATH'') }}:/home/{{ username }}/.local/bin/aws'
     - PATH: '{{ lookup(''env'', ''PATH'') }}:/home/{{ username }}/.entando/ent/v7.0.1/cli/v7.0.0/bin'
   tasks:
   
    - name: Collect all Entando application logs with ent
      shell: |
          source /home/{{ username }}/.entando/activate --quiet --force 2>/dev/null
          ent namespace {{ namespace }}
          ent diag
   
    - name: Create Dir Logs
      shell: mkdir -p /home/{{ username }}/log-collector/{{ appname }}-v{{ source }}/results
      
    - name: Collect all Entando application logs from pods
      shell: kubectl get pods -n {{ namespace }} --no-headers | awk '{print $1}' | while read PODS;do kubectl logs $PODS -n {{ namespace }} > /home/{{ username }}/log-collector/{{ appname }}-v{{ source }}/$PODS.log;done
      
    - name: Copy Ent results
      shell: mv /home/{{ username }}/.entando/reports/* /home/{{ username }}/log-collector/{{ appname }}-v{{ sourceN }}
      
    - name: Extract Ent results
      shell: chdir=/home/{{ username }}/log-collector/{{ appname }}-v{{ source }}  tar -xvf *.tgz