---
 - hosts: AWX
   become_user: "{{ username }}"
   tasks:
   
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }}/terraform-test/learn-terraform-provision-eks-cluster ./hub-tool tag ls entando/entando-component-manager --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-component-manager://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOCOMPONENTMANAGER; do echo "$ENTANDOCOMPONENTMANAGER";done
      register: ENTANDOCOMPONENTMANAGER
    - set_fact:
       CLIENTSECRET: "{{ ENTANDOCOMPONENTMANAGER.stdout }}"
       
#    - debug:
#        var: CLIENTSECRET
      
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }}/terraform-test/learn-terraform-provision-eks-cluster ./hub-tool tag ls entando/entando-de-app-wildfly --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-de-app-wildfly://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODEAPPWILDFLY; do echo "$ENTANDODEAPPWILDFLY";done
      register: ENTANDODEAPPWILDFLY
    - set_fact:
       CLIENTSECRET: "{{ ENTANDODEAPPWILDFLY.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }}/terraform-test/learn-terraform-provision-eks-cluster ./hub-tool tag ls entando/entando-de-app-eap --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-de-app-eap://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODEAPPEAP; do echo "$ENTANDODEAPPEAP";done
      register: ENTANDODEAPPEAP
    - set_fact:
       CLIENTSECRET: "{{ ENTANDODEAPPEAP.stdout }}"

    - name: Generate cypress config file
      template:
        src: ./templates/namespace-resources_custom.j2
        dest: /home/{{ username }}/namespace-resources_custom.yaml
