---
 - hosts: AWX
   become: yes
   become_user: "{{ username }}"
   tasks:
    - name: Login in
      command: chdir=/home/openshift ./oc login api.{{ openshift_url }}:6443 -u admin -p {{ password1 }} --insecure-skip-tls-verify=true

    - name: Create Project
      shell: chdir=/home/openshift ./oc create namespace {{ namespace }}
      
    - name: Copy certificate-script Script
      template:
        src: ./templates/selfsign-certificate-script.js
        dest: /home/openshift/selfsign-certificate-script.sh
 
    - name: Make script executable
      shell: chdir=/home/openshift chmod +x selfsign-certificate-script.sh

    - name: Run certificates script
      shell: chdir=/home/openshift ./selfsign-certificate-script.sh
      
    - name: Create secret
      shell: chdir=/home/openshift ./oc create secret tls entando-tls-secret --key="{{ appname }}.apps.{{ openshift_url }}-server-key.pem" --cert="{{ appname }}.apps.{{ openshift_url }}-server-cert.pem" -n {{ namespace }}
    
    - name: Create ca secret
      shell: chdir=/home/openshift ./oc create secret generic entando-ca-cert-secret --from-file="{{ appname }}.apps.{{ openshift_url }}-ca-cert.pem" -n {{ namespace }}
    
    - name: Remove certificates from host
      shell: chdir=/home/openshift rm  {{ appname }}.apps.{{ openshift_url }}*.pem

    - name: Create mysql-secrets
      shell: |
        chdir=/home/openshift ./oc create secret generic mysql-secret --from-literal username=automation --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic oracle-secret --from-literal username=automation --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic postgres-secret --from-literal username=automation --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic default-sso-in-namespace-db-secret --from-literal username=automationsso --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic {{appname}}-portdb-{{ dbmode }} --from-literal username=automationport --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic {{appname}}-servdb-{{ dbmode }} --from-literal username=automationserv --from-literal password=myP4ssw0rd -n {{ namespace }}
        chdir=/home/openshift ./oc create secret generic {{appname}}-dedb-{{ dbmode }} --from-literal username=automationecr --from-literal password=myP4ssw0rd -n {{ namespace }}

    - name: Copy operator-config
      template:
        src: ./templates/{{operatorconfig}}.j2
        dest: /home/openshift/{{operatorconfig}}.yaml

    - name: Install operatorscript on namespace scope
      shell: chdir=/home/openshift ./oc apply -f {{operatorconfig}}.yaml -n {{ namespace }}      

    - name: Copy Operator Script
      template:
        src: ./templates/entando-subscription.j2
        dest: /home/openshift/entando-subscription.yaml

    - name: Install operatorscript on namespace scope
      shell: chdir=/home/openshift ./oc apply -f entando-subscription.yaml -n {{ namespace }}

    - name: Sleep for 400 seconds and continue with play
      wait_for:
        timeout: 100

    - name: Scale down Operator deployment
      shell: chdir=/home/{{ username }} ./oc scale deployment entando-operator -n {{ namespace }} --replicas=0
      
    - name: Build operator deployment with latest images
      shell: chdir=/home/{{ username }} ./oc get clusterserviceversion -n {{ namespace }} -o yaml > entando-operator-openshift.yaml

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/app-builder --sort updated | awk 'FNR==2{print $1}' | sed 's/appbuilder://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOAPPBUILDER; do echo "$ENTANDOAPPBUILDER";done
      register: ENTANDOAPPBUILDER
    - set_fact:
       ENTANDOAPPBUILDER: "{{ ENTANDOAPPBUILDER.stdout }}"
           
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/app-builder --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOAPPBUILDER;do echo  "$SHAENTANDOAPPBUILDER";done
      register: SHAENTANDOAPPBUILDER
    - set_fact:
       SHAENTANDOAPPBUILDER: "{{ SHAENTANDOAPPBUILDER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entandobuilduser/entando-k8s-index --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-index://g' | sed 's/entandobuilduser//g' |sed 's/\///g' | while read  ENTANDOKI; do echo "$ENTANDOKI";done
      register: ENTANDOKI
    - set_fact:
       ENTANDOKI: "{{ ENTANDOKI.stdout }}"
           
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entandobuilduser/entando-k8s-index --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOKI;do echo  "$SHAENTANDOKI";done
      register: SHAENTANDOKI
    - set_fact:
       SHAENTANDOKI: "{{ SHAENTANDOKI.stdout }}"
 
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-component-manager --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-component-manager://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOCOMPONENTMANAGER; do echo "$ENTANDOCOMPONENTMANAGER";done
      register: ENTANDOCOMPONENTMANAGER
    - set_fact:
       ENTANDOCOMPONENTMANAGER: "{{ ENTANDOCOMPONENTMANAGER.stdout }}"
       
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-component-manager --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOCOMPONENTMANAGER;do echo  "$SHAENTANDOCOMPONENTMANAGER";done
      register: SHAENTANDOCOMPONENTMANAGER
    - set_fact:
       SHAENTANDOCOMPONENTMANAGER: "{{ SHAENTANDOCOMPONENTMANAGER.stdout }}"  
           
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-de-app-wildfly --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-de-app-wildfly://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODEAPPWILDFLY; do echo "$ENTANDODEAPPWILDFLY";done
      register: ENTANDODEAPPWILDFLY
    - set_fact:
       ENTANDODEAPPWILDFLY: "{{ ENTANDODEAPPWILDFLY.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-de-app-wildfly --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDODEAPPWILDFLY;do echo  "$SHAENTANDODEAPPWILDFLY";done
      register: SHAENTANDODEAPPWILDFLY
    - set_fact:
       SHAENTANDODEAPPWILDFLY: "{{ SHAENTANDODEAPPWILDFLY.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-de-app-eap --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-de-app-eap://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODEAPPEAP; do echo "$ENTANDODEAPPEAP";done
      register: ENTANDODEAPPEAP
    - set_fact:
       ENTANDODEAPPEAP: "{{ ENTANDODEAPPEAP.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-de-app-eap --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDODEAPPEAP;do echo  "$SHAENTANDODEAPPEAP";done
      register: SHAENTANDODEAPPEAP
    - set_fact:
       SHAENTANDODEAPPEAP: "{{ SHAENTANDODEAPPEAP.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-app-controller --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-app-controller://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOAPPCONTROLLER; do echo "$ENTANDOAPPCONTROLLER";done
      register: ENTANDOAPPCONTROLLER
    - set_fact:
       ENTANDOAPPCONTROLLER: "{{ ENTANDOAPPCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-app-controller --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOAPPCONTROLLER;do echo  "$SHAENTANDOAPPCONTROLLER";done
      register: SHAENTANDOAPPCONTROLLER
    - set_fact:
       SHAENTANDOAPPCONTROLLER: "{{ SHAENTANDOAPPCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-plugin-controller --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-plugin-controller://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOPLUGINCONTROLLER; do echo "$ENTANDOPLUGINCONTROLLER";done
      register: ENTANDOPLUGINCONTROLLER
    - set_fact:
       ENTANDOPLUGINCONTROLLER: "{{ ENTANDOPLUGINCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-plugin-controller --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOPLUGINCONTROLLER;do echo  "$SHAENTANDOPLUGINCONTROLLER";done
      register: SHAENTANDOPLUGINCONTROLLER
    - set_fact:
       SHAENTANDOPLUGINCONTROLLER: "{{ SHAENTANDOPLUGINCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-dbjob --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-dbjob://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODBJOB; do echo "$ENTANDODBJOB";done
      register: ENTANDODBJOB
    - set_fact:
       ENTANDODBJOB: "{{ ENTANDODBJOB.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-dbjob --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDODBJOB;do echo  "$SHAENTANDODBJOB";done
      register: SHAENTANDODBJOB
    - set_fact:
       SHAENTANDODBJOB: "{{ SHAENTANDODBJOB.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-keycloak-controller --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-keycloak-controller://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOKKCONTROLLER; do echo "$ENTANDOKKCONTROLLER";done
      register: ENTANDOKKCONTROLLER
    - set_fact:
       ENTANDOKKCONTROLLER: "{{ ENTANDOKKCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-keycloak-controller --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOKKCONTROLLER;do echo  "$SHAENTANDOKKCONTROLLER";done
      register: SHAENTANDOKKCONTROLLER
    - set_fact:
       SHAENTANDOKKCONTROLLER: "{{ SHAENTANDOKKCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-database-service-controller --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-database-service-controller://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDODBSVCCONTROLLER; do echo "$ENTANDODBSVCCONTROLLER";done
      register: ENTANDODBSVCCONTROLLER
    - set_fact:
       ENTANDODBSVCCONTROLLER: "{{ ENTANDODBSVCCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-database-service-controller --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDODBSVCCONTROLLER;do echo  "$SHAENTANDODBSVCCONTROLLER";done
      register: SHAENTANDODBSVCCONTROLLER
    - set_fact:
       SHAENTANDODBSVCCONTROLLER: "{{ SHAENTANDODBSVCCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-app-plugin-link-controller --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-app-plugin-link-controller://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOAPPPLUGINCONTROLLER; do echo "$ENTANDOAPPPLUGINCONTROLLER";done
      register: ENTANDOAPPPLUGINCONTROLLER
    - set_fact:
       ENTANDOAPPPLUGINCONTROLLER: "{{ ENTANDOAPPPLUGINCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-app-plugin-link-controller --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOAPPPLUGINCONTROLLER;do echo  "$SHAENTANDOAPPPLUGINCONTROLLER";done
      register: SHAENTANDOAPPPLUGINCONTROLLER
    - set_fact:
       SHAENTANDOAPPPLUGINCONTROLLER: "{{ SHAENTANDOAPPPLUGINCONTROLLER.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-service --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-service://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOSERVICE; do echo "$ENTANDOSERVICE";done
      register: ENTANDOSERVICE
    - set_fact:
       ENTANDOSERVICE: "{{ ENTANDOSERVICE.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-service --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOSERVICE;do echo  "$SHAENTANDOSERVICE";done
      register: SHAENTANDOSERVICE
    - set_fact:
       SHAENTANDOSERVICE: "{{ SHAENTANDOSERVICE.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-process-driven-plugin --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-process-driven-plugin://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOPDPLUGIN; do echo "$ENTANDOPDPLUGIN";done
      register: ENTANDOPDPLUGIN
    - set_fact:
       ENTANDOPDPLUGIN: "{{ ENTANDOPDPLUGIN.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-process-driven-plugin --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOPDPLUGIN;do echo  "$ENTANDOPDPLUGIN";done
      register: SHAENTANDOPDPLUGIN
    - set_fact:
       SHAENTANDOPDPLUGIN: "{{ SHAENTANDOPDPLUGIN.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-keycloak --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-keycloak://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOKK; do echo "$ENTANDOKK";done
      register: ENTANDOKK
    - set_fact:
       ENTANDOKK: "{{ ENTANDOKK.stdout }}"
       
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-keycloak --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOKK;do echo  "$SHAENTANDOKK";done
      register: SHAENTANDOKK
    - set_fact:
       SHAENTANDOKK: "{{ SHAENTANDOKK.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-controller-coordinator --sort updated | awk 'FNR==2{print $1}' | sed 's/entando-k8s-controller-coordinator://g' | sed 's/entando//g' |sed 's/\///g' | while read  ENTANDOCONTROLLERCOORDINATOR; do echo "$ENTANDOCONTROLLERCOORDINATOR";done
      register: ENTANDOCONTROLLERCOORDINATOR
    - set_fact:
       ENTANDOCONTROLLERCOORDINATOR: "{{ ENTANDOCONTROLLERCOORDINATOR.stdout }}"
       
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} hub-tool tag ls entando/entando-k8s-controller-coordinator --sort updated |awk 'FNR==2{print $2}' | while read  SHAENTANDOCONTROLLERCOORDINATOR;do echo  "$SHAENTANDOCONTROLLERCOORDINATOR";done
      register: SHAENTANDOCONTROLLERCOORDINATOR
    - set_fact:
       SHAENTANDOCONTROLLERCOORDINATOR: "{{ SHAENTANDOCONTROLLERCOORDINATOR.stdout }}"

    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-component-manager@.*/entando-component-manager@{{ SHAENTANDOCOMPONENTMANAGER }}/g" entando-operator-openshift.yaml > entando-operator-opensift-modified.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-de-app-wildfly@.*/entando-de-app-wildfly@{{ SHAENTANDODEAPPWILDFLY }}/g" entando-operator-opensift-modified.yaml > entando-operator-opensift-modified1.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-de-app-eap@.*/entando-de-app-eap@{{ SHAENTANDODEAPPEAP }}/g" entando-operator-opensift-modified1.yaml > entando-operator-opensift-modified2.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-app-controller@.*/entando-k8s-app-controller@{{ SHAENTANDOAPPCONTROLLER }}/g" entando-operator-opensift-modified2.yaml > entando-operator-opensift-modified3.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-plugin-controller@.*/entando-k8s-plugin-controller@{{ SHAENTANDOPLUGINCONTROLLER }}/g" entando-operator-opensift-modified3.yaml > entando-operator-opensift-modified4.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-dbjob@.*/entando-k8s-dbjob@{{ SHAENTANDODBJOB }}/g" entando-operator-opensift-modified4.yaml > entando-operator-opensift-modified5.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-keycloak-controller@.*/entando-k8s-keycloak-controller@{{ SHAENTANDOKKCONTROLLER }}/g" entando-operator-opensift-modified5.yaml > entando-operator-opensift-modified6.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-database-service-controller@.*/entando-k8s-database-service-controller@{{ SHAENTANDODBSVCCONTROLLER }}/g" entando-operator-opensift-modified6.yaml > entando-operator-opensift-modified7.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-app-plugin-link-controller@.*/entando-k8s-app-plugin-link-controller@{{ SHAENTANDOAPPPLUGINCONTROLLER }}/g" entando-operator-opensift-modified.yaml > entando-operator-opensift-modified8.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-service@.*/entando-k8s-service@{{ SHAENTANDOSERVICE }}/g" entando-operator-opensift-modified8.yaml > entando-operator-opensift-complete.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-process-driven-plugin@.*/entando-process-driven-plugi@{{ SHAENTANDOPDPLUGIN }}/g" entando-operator-opensift-modified9.yaml > entando-operator-opensift-modified10.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-keycloak@.*/entando-keycloak@{{ SHAENTANDOKK }}/g" entando-operator-opensift-modified10.yaml > entando-operator-opensift-modified11.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/app-builder@.*/app-builder@{{ SHAENTANDOAPPBUILDER }}/g" entando-operator-opensift-modified11.yaml > entando-operator-opensift-modified12.yaml
    - name: Retrive clientsecret
      shell: chdir=/home/{{ username }} sed "s/entando-k8s-controller-coordinator@.*/entando-k8s-controller-coordinator@{{ SHAENTANDOCONTROLLERCOORDINATOR }}/g" entando-operator-opensift-modified12.yaml > entando-operator-opensift-complete.yaml

    - name: Apply operator deployment updated
      shell: chdir=/home/{{ username }} ./oc replace -f entando-operator-opensift-complete.yaml -n {{ namespace }}
      
    - name: Scale up operator
      shell: chdir=/home/{{ username }} ./oc scale deployment entando-operator -n {{ namespace }} --replicas=1


    - name: Copy Entando App Script
      template:
        src: ./templates/{{entandoappconfig}}.j2
        dest: /home/openshift/{{entandoappconfig}}.yaml

    - name: Copy dbms external svc
      template:
        src: ./templates/dbms-{{ dbms }}.j2
        dest: /home/openshift/dbms-{{ dbms }}.yaml

    - name: Install dbms svc
      shell: chdir=/home/openshift ./oc apply -f dbms-{{ dbms }}.yaml -n {{ namespace }}

    - name: sleep for 10 seconds and continue with play
      wait_for: timeout=40

    - name: Install Entando App on namespace scope
      shell: chdir=/home/openshift ./oc apply -f {{entandoappconfig}}.yaml -n {{ namespace }}

    - name: Sleep for 400 seconds and continue with play
      wait_for:
        timeout: 400