---
 - hosts: AWX
   become: yes
   become_user: "{{ username }}"
   environment:
     PATH: '{{ lookup(''env'', ''PATH'') }}:/home/{{ username }}/.local/bin/aws'
   tasks:
   
    - name: Select working dir
      command: cd /home/{{ username }}
      
    - name: Copy certificate-script Script
      template:
        src: ./templates/selfsign-certificate-script-kubernetes.js
        dest: /home/openshift/selfsign-certificate-script-kubernetes.sh
 
    - name: Make script executable
      shell: chdir=/home/openshift chmod +x selfsign-certificate-script-kubernetes.sh

    - name: Run certificates script
      shell: chdir=/home/openshift ./selfsign-certificate-script-kubernetes.sh
      
    - name: Create secret
      shell: chdir=/home/openshift kubectl create secret tls entando-tls-secret --key="{{ appname }}.{{ urlingress }}-server-key.pem" --cert="{{ appname }}.{{ urlingress }}-server-cert.pem" -n {{ namespace }}
    
    - name: Create ca secret
      shell: chdir=/home/openshift kubectl create secret generic entando-ca-cert-secret --from-file="{{ appname }}.{{ urlingress }}-ca-cert.pem" -n {{ namespace }}
    
    - name: Remove certificates from host
      shell: chdir=/home/openshift rm  {{ appname }}.{{ urlingress }}*.pem
      
    - name: Copy Installation script Script
      template:
        src: ./templates/entando_installation_script_{{ dbmode }}.j2
        dest: /home/{{ username }}/entando_installation_script_{{ dbmode }}.sh

    - name: Change Permission 
      shell: chdir=/home/{{ username }} chmod +x entando_installation_script_{{ dbmode }}.sh
      
    - name: Execute installation script
      command: /home/{{ username }}/./entando_installation_script_{{ dbmode }}.sh {{ namespace }} {{ appname }}
      register: results
      
    - name: Print Results
      debug:
        msg: "{{ results }}"
