---
 - hosts: AWX
   become_user: azureuser
   tasks:
   
    - name: Select working dir
      command: cd terraform-test/learn-terraform-provision-eks-cluster/
      
    - name: Get kubernetes config
      shell: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)
      args:
        chdir: terraform-test/learn-terraform-provision-eks-cluster/
      
    - name: Copy Installation script Script
      template:
        src: ./templates/entando_installation_script.j2
        dest: entando_installation_script.sh
        
    - name: Change Permission 
      shell: chmod +x entando_installation_script.sh
      
    - name: Execute installation script
      shell: ./entando_installation_script.sh {{ namespaces }} {{ APPNAME }}
      register: results
      
    - name: Print Results
      debug:
        msg: "{{ results }}"
        
    - name: Wait untill the Application is up
      wait_for: timeout=200
      delegate_to: localhost
