---
 - hosts: AWX
   become_user: azureuser
   tasks:
   
    - name: Select working dir
      command: chdir /home/azureuser/terraform-test/learn-terraform-provision-eks-cluster
      
    - name: Copy Installation script Script
      template:
        src: ./templates/entando_installation-script.js
        dest: entando_installation-script.sh
        
    - name: Change Permission 
      shell: chmod +x entando_installation-script.sh
      
    - name: Execute installation script
      shell: ./entando_installation-script.sh entando quickstart
      register: results
      
    - name: Print Results
      debug:
        msg: "{{ results }}"
