---
 - hosts: AWX
   become_user: azureuser
   tasks:

    - name: Login in
      shell: oc login {{ openshift_url }} -u admin -p {{ password }} --insecure-skip-tls-verify=true
      
    - name: Scale Down test projects
      shell: |
        oc get deploy -A --no-headers | grep 'qe-' | awk '{print $2,$1}' | while read DEPLOY NAMESPACE;do oc scale --replicas=0 deployment/$DEPLOY -n $NAMESPACE; done
        oc get deploy -A --no-headers | grep 'test-' | awk '{print $2,$1}' | while read DEPLOY NAMESPACE;do oc scale --replicas=0 deployment/$DEPLOY -n $NAMESPACE; done
    - name: Logout
      shell: oc logout
